### PR TITLE
fixes, clarifies.

### PR DESCRIPTION
**Pull request by cahlan**

### CODE REVIEW

**Comment by tylermcginnis** [comment]
@jacob-israel-turner Will you look at this and merge if it's good? There are a bunch of changes and I don't think either of us saw this initially.

**Comment by jacob-israel-turner** [comment]
This probably solves all our problems.  I'll take a look at it.

**Comment by tylermcginnis** [comment]
I don't know, I have a lot of problems...

**Comment by asBrettisay** [comment]
@jacob-israel-turner never looked at this, times up, closing.

**Comment by cahlan** [comment]
😂

**Comment by jacob-israel-turner** [comment]
Sorry guys.  I'll get into it sometime this Spring.

**Pull request closed without merging**
